/**
 * Turns the eleven Iconify icons this site uses into one inline SVG component.
 *
 * They were being fetched from api.iconify.design at runtime, per visitor, by
 * a client component that rendered an empty span until the JavaScript loaded
 * and the network answered. On a slow connection that is a page of blank gaps
 * that fill in late. Eleven icons is 6KB of paths — smaller than the library
 * that fetched them.
 */

const fs = require('fs');
const path = require('path');

const data = JSON.parse(fs.readFileSync(path.join(__dirname, 'icons.json'), 'utf8'));

/** The names used in the codebase, mapped to whatever Iconify actually returned. */
const WANTED = [
  'apartment-rounded',
  'check-small-rounded',
  'handshake-rounded',
  'handyman-rounded',
  'home-repair-service-rounded',
  'library-books-rounded',
  'schedule-rounded',
  'school-rounded',
  'track-changes-rounded',
  'travel-explore-rounded',
  'workspace-premium-rounded',
];

function resolve(name) {
  if (data.icons[name]) return data.icons[name];
  // Iconify resolves some names to a canonical alias (handyman-rounded -> handyman).
  const alias = data.aliases?.[name];
  if (alias?.parent && data.icons[alias.parent]) return data.icons[alias.parent];
  const stripped = name.replace(/-rounded$/, '');
  if (data.icons[stripped]) return data.icons[stripped];
  return null;
}

const entries = [];
for (const name of WANTED) {
  const icon = resolve(name);
  if (!icon) {
    console.error('MISSING:', name);
    process.exitCode = 1;
    continue;
  }
  // Escape backticks and ${ so the body can sit in a template-free string literal.
  const body = icon.body.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  entries.push(`  '${name}': '${body}',`);
}

const file = `/**
 * The site's icons, inline.
 *
 * These were loaded through @iconify/react, which fetches an icon's paths from
 * api.iconify.design at runtime. That meant a third-party network round trip
 * before any icon could appear, inside a client component that rendered an
 * empty span until it resolved — so on a slow connection the page showed a row
 * of blank squares and filled them in late, if at all.
 *
 * There are eleven of them. Inlined, they are a few kilobytes of path data that
 * render with the HTML, server-side, with no JavaScript and no request. The
 * component is deliberately NOT a client component: an icon has no behaviour.
 *
 * Regenerated by scripts/gen-icons.js if the set ever changes.
 */

/** Path data, keyed by the Iconify name the codebase already used. */
const PATHS: Record<string, string> = {
${entries.join('\n')}
};

export interface IconWrapperProps {
  /** An Iconify name, e.g. "material-symbols:school-rounded". */
  icon: string;
  className?: string;
  ariaHidden?: boolean;
}

/**
 * Kept under its original name and props so every existing call site works
 * unchanged — this is a swap of the implementation, not of the interface.
 */
export function IconWrapper({ icon, className, ariaHidden = true }: IconWrapperProps) {
  const name = icon.includes(':') ? icon.slice(icon.indexOf(':') + 1) : icon;
  const body = PATHS[name];

  // An unknown icon reserves its space rather than collapsing the layout around
  // it, which is what a missing icon used to do here.
  if (!body) return <span className={className} aria-hidden={ariaHidden} />;

  return (
    <svg
      viewBox="0 0 24 24"
      className={className}
      aria-hidden={ariaHidden}
      focusable="false"
      fill="currentColor"
      dangerouslySetInnerHTML={{ __html: body }}
    />
  );
}

export default IconWrapper;
`;

const out = path.join(__dirname, 'IconWrapper.generated.tsx');
fs.writeFileSync(out, file);
console.log('wrote', out, '—', entries.length, 'icons');
